spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:payment-service;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true


kakao:
  admin: e217481aeaeb6c14f8f10912b441f961
endpoint:
  apigateway-service: http://localhost:3000