server:
  port: 8100
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: payment-service
  config:
    activate:
      on-profile: prod
    import: optional:configserver:http://config-service:8888
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"
          - "health"
