server:
  port: 8100
spring:
  application:
    name: payment-service
  config:
    activate:
      on-profile: local, dev, local
    import: optional:configserver:http://localhost:8888
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:payment-service;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"